### ISSUE TITLE
Crashes at launch

### ISSUE THREAD

**Issue by lionirdeadman** [flathub/org.freedesktop.Piper#5]
Log :
```Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/piper/application.py", line 52, in do_activate
    window = Window(self._ratbag, application=self)
  File "/app/lib/python3.7/site-packages/piper/window.py", line 69, in __init__
    self._present_mouse_perspective(ratbag.devices[0])
  File "/app/lib/python3.7/site-packages/piper/window.py", line 147, in _present_mouse_perspective
    mouse_perspective.set_device(device)
  File "/app/lib/python3.7/site-packages/piper/mouseperspective.py", line 90, in set_device
    self.stack.add_titled(ResolutionsPage(device), "resolutions", _("Resolutions"))
  File "/app/lib/python3.7/site-packages/piper/resolutionspage.py", line 66, in __init__
    self._init_ui()
  File "/app/lib/python3.7/site-packages/piper/resolutionspage.py", line 71, in _init_ui
    mousemap = MouseMap("#Buttons", self._device, spacing=20, border_width=20)
  File "/app/lib/python3.7/site-packages/piper/mousemap.py", line 111, in __init__
    svg_bytes = get_svg(ratbagd_device.model)
  File "/app/lib/python3.7/site-packages/piper/svg.py", line 32, in get_svg
    if model.startswith('usb:') or model.startswith('bluetooth:'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by doraskayo** [comment]
The above is missing the actual errror message:
``` bash
Gtk-Message: 11:43:05.087: Failed to load module "pk-gtk-module"
```

**Comment by whot** [comment]
Are you running against libratbag 0.9.905 or later?

**Comment by lionirdeadman** [comment]
No, I'm using the latest on Fedora : 0.9.904

**Comment by doraskayo** [comment]
Same here, 0.9.904-2.fc30 specifically.

**Comment by whot** [comment]
right, that'd explain it. I just pushed 906 into Fedora 30 and rawhide, that should fix the issue

**Comment by doraskayo** [comment]
I can confirm Piper 0.2.905 works after updating `libratbag-ratbagd` using the following command:
``` bash
sudo dnf update --enablerepo=updates-testing libratbag-ratbagd-0.9.906-1.fc30.x86_64
```
